specVersion: 0.2.0
name: subqlHelloWorld
version: 0.0.4
description: >-
  This project can be use as a starting point for developing your SubQuery
  project
repository: 'https://github.com/subquery/subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://127.0.0.1:9944'
  genesisHash: '0xe3893de85519668fed5fe6e06d49df2ec9249a08dcd635e863b440c7510745c5'
  #endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
  #genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3' # Polkadot
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
